/*
 * a11y-overlay.js — live element / component highlighter
 *
 * Toggles (keyboard-only UI):
 *   ?    — show/hide help
 *   L    — Landmarks (header, nav, main, section, footer, aside, form, article)
 *   H    — Headings outline (h1–h6)
 *   I    — Interactive (a, button, input, textarea, select, [role=button], [tabindex])
 *   M    — Forms / labeling audit
 *   T    — Interactive targets smaller than 24×24 CSS px without spacing relief
 *   A    — Image audit
 *   R    — Repeating components (siblings with matching DOM signature)
 *   F    — Focus / tab order (numbered badges)
 *   D    — Depth hierarchy (nested outline colors per DOM depth)
 *   G    — Grid (implicit block boundaries of every block-level element)
 *   N    — Place one note
 *   W    — Place one arrow
 *   V    — Deselect / exit placement
 *   X    — Kill overlay
 *
 * Install: <script src="a11y-overlay.js"></script>   OR use the bookmarklet.
 *
 * Source of truth lives in src/overlay/*.js. The shipped root-level
 * a11y-overlay.js file is generated by scripts/build_overlay.py.
 *
 * No DOM nodes or stylesheets on the host page are modified. All overlay chrome
 * lives inside a shadow root attached to a fixed-position host <div> appended
 * to <html>. Renders are RAF-throttled and fire on scroll / resize / mutation.
 */
(function () {
  function install() {
    if (window.__a11yOverlayInstalled) {
      const existingRuntime = window.__a11yOverlayInstalled;
      if (
        (typeof existingRuntime === 'object' || typeof existingRuntime === 'function') &&
        typeof existingRuntime.toggleHelp === 'function'
      ) {
        existingRuntime.toggleHelp();
      }
      return;
    }

    // Support early agent-side injection via addInitScript().
    if (!document.documentElement || !document.body) {
      window.addEventListener('DOMContentLoaded', install, { once: true });
      return;
    }
